[package]
name = "oozebot-protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.9.4"
serde = { version = "1.0.226", features = ["derive"] }
serde_json = "1.0.145"
serde_with = "3.15.0"
thiserror = "2.0.16"
tokio-tungstenite = "0.27.0"
