[package]
name = "onnx_parser"
version = "0.1.0"
edition = "2024"

[build-dependencies]
prost-build = "0.14.1"

[dependencies]
prost = "0.14.1"
prost-types = "0.14.1"
wasm-bindgen = "0.2.100"
web-sys = { version = "0.3.77", features = ["console"] }
