[package]
name = "frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
gloo = "0.11.0"
onnx-ir = "0.18.0"
prost = "0.14.1"
wasm-bindgen = "0.2.100"
web-sys = "0.3.77"
yew = { version = "0.21.0", features = ["csr"] }
