[package]
name = "ez_youtube_chat"
version = "0.1.0"
edition = "2024"

[dependencies]
oauth2 = { version = "5.0.0", features = ["reqwest"] }
open = "5.3.2"
reqwest = { version = "0.12.15", features = ["json"] }
serde = "1.0.219"
serde_json = "1.0.140"
thiserror = "2.0.12"
url = "2.5.4"
