[package]
name = "futures_combinators"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
pin-project-lite = "0.2.16"
tokio = { version = "1.48.0", features = ["test-util", "full"] }
tokio-stream = "0.1.17"
tokio-util = "0.7.17"
