[package]
name = "suzi_web"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
gloo-console = "0.3.0"
gloo-net = "0.6.0"
serde = "1.0.219"
wasm-bindgen-futures = "0.4.50"
yew = { version = "0.21.0", features = ["csr"] }
yew-router = "0.18.0"
